### PR TITLE
Issue #3 - refactor to support ajax

### PR DESCRIPTION
**Pull request by craigweston**
I have added ajax support to the plugin to support real time search. This required a refactor to the some of the core functionality, as you mentioned would be necessary in Issue #3.

Ajax is supported by having that data function return a deferred object, which gives flexibility to the user to decide how they want to implement the lookup functionality. 

Here is an example using ajax:

```
$('#comment').suggest('@', {
  data: function(q) {
    if (q && q.length >= 3) {
      return $.getJSON("users/lookup.json", { q:q });
    }
  },
  map: function(user) {
    return {
      value: user.username,
      text: '<strong>'+user.username+'</strong> <small>'+user.fullname+'</small>'
    }
  }
});
```

Since you were previously pre-rendering the dropdown layout from the initial data and using the hidden class to toggle visible items when searching, I had to modify the building of the items to occur in ```lookup``` instead of ```__build```, since we can't know whether a deferred is going to be returned or not until a query is available.

In the case when a deferred is returned, we delay building and showing the dropdown until the deferred has been resolved and the data is available:

From ```lookup```:
```
      if(data && $.isFunction(data.promise)) {
        data.done(function(data) {
          if(data && data.length > options.filter.limit) {
            data = data.slice(0, options.filter.limit);
          }
          that.$items = that.__buildItems(data);
          that.__lookup(q, that.$items);
        });
      }
```

If no deferred is returned or the data was provided directly as an array, then we build the dropdown items and cache them in ```this.$items```, using the same execution path that was in place originally.

Also note, that on line 448: 
```
   this.$items = undefined;
```
I clear the items, since we cannot assume that data from the external function has not changed since the last query. This prevents stale data from the previous query from being shown in the dropdown when the query text has changed (backspace pressed or a new @ character is pressed). This resetting of the ```this.$items``` does not occur when the data is provided directly via the initial configuration.

Please let me know if you have any questions or concerns.

Thank you.

### CODE REVIEW

**Comment by lodev09** [comment]
wow thank you for taking time working on this feature. I will take a look as soon as I can and will let you know. 

Thanks :)

**Comment by craigweston** [comment]
No problem, thanks for making this plugin :)

**Comment by lodev09** [comment]
@craigweston good job on this one man! just got the time to test it on one of my project. Thanks again :)

**Comment by craigweston** [comment]
No problem. Glad to see it got merged and is being used :)

**Comment by robjbrain** [comment]
It seems like you removed this on Jan 29 when you where 'removing unwanted code'

[https://github.com/lodev09/bootstrap-suggest/commit/8c7cbddc102aff0a5172059adacce81c8c27acc3](https://github.com/lodev09/bootstrap-suggest/commit/8c7cbddc102aff0a5172059adacce81c8c27acc3) 

@craigweston @lodev09

**Comment by robjbrain** [comment]
Actually I may be wrong about that, it was a large and confusing commit to read. Nonetheless AJAX doesn't seem to be working. The data function only gets called once and `q` is always undefined.

**Comment by craigweston** [comment]
Thanks for reporting. @robjbrain I believe you are correct, it looks like the AJAX code was removed in this commit: [8c7cbdd](https://github.com/lodev09/bootstrap-suggest/commit/8c7cbddc102aff0a5172059adacce81c8c27acc3) . @lodev09 were you aware of this?

**Comment by lodev09** [comment]
oopssss! I think committed the one from the master branch and updated the gh-pages branch, sorry abou that.. @craigweston can you please take a look at your mod related to ajax and see if you could put it back in. Thanks :)

**Comment by craigweston** [comment]
I'll try to get this added back in soon.

**Comment by lodev09** [comment]
@craigweston this is fixed.. I reverted some code from this [commit](https://github.com/lodev09/bootstrap-suggest/commit/e9d695b3e52923349c441ab614f920a80a19d9b7) and implemented those "unwanted code" fix.

**Pull request merged**
