### PR TITLE
# Made it work with BS4

### PR DESCRIPTION
**Pull request by WilliamStam**
# Made it work with BS4
+ Added a scss file for us "normal" folk :P

### CODE REVIEW

**Comment by lodev09** [comment]
Thanks @WilliamStam. Is there a reason to replace `ul` with `div` for BS4?

**Comment by WilliamStam** [comment]
BS4 doesnt include any `ul>li` examples on their site, usually that means that they trying to move away from old ways of doing things. the div way gives more options aswell like headers etc. (does still work it seems http://jsfiddle.net/aq9Laaew/154644/)

i had issues previously getting `ul>li` dropdowns to play nicely in my project so i just change it to `div`'s now by default. you can probably keep the `ul>li` way in i suppose. right now im including `div`s in mine so naturally the `div>div` is better than a `li>div` 

```
map: function(user) {
	return {
	    value: user.column_name,
	    text: '<div><code>'+user.column_name+'</code></div><div><small>'+user.description+'</small></div>'
	}
},
```

**Comment by lodev09** [comment]
@WilliamStam can you rebase and submit PR again please? I'll merge in v2 version just for bs4

**Comment by lodev09** [comment]
BS4 support is now in development under `v2`. closing this

**Pull request closed without merging**
